### ISSUE TITLE
Semicolons after function definition causes all subsequent lines to be ignored

### ISSUE THREAD

**Issue by Lenny-the-burger** [radian628/desmoscript#1]
The following code:
```
fn i(v) {
    return A(1-v) + B(v)
};'

P = i (5);

L = 2.0;
```

results in p and l not being compiled. If the semicolon is removed after i(v) there are no issues.

**Comment by radian628** [comment]
This is now fixed--- putting a semicolon after a function now produces an error message. (or at least it should lol)
