### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by Subroutine7901** [radian628/desmoscript#10]
.DS_Store is a file that stores icon placement data, along with other related things in Mac OS. This happens to be the exact type of file that .gitignore was made to help with, so it doesn't get it the way. Not a bug, just a minor suggestion.

**Comment by radian628** [comment]
Thanks for the tip! I'm in the process of making a massive rewrite of this (the version on the main branch as of typing this is quite old). I've implemented this change (removing .DS_Store and adding to .gitignore) on the new version which will go onto main quite soon.

**Comment by Subroutine7901** [comment]
Great! I'll watch the repo to get updates when you finish.
